@echo off
echo Debug Start...
echo [1/3] MongoDB...
start "DB" /B cmd /c "mongod --dbpath=C:\Users\DELL\OneDrive\Desktop\Emotions\mongodb_data > mongodb_debug.log 2>&1"
timeout /t 5
echo [2/3] Backend...
start "Backend" /B cmd /c "python api.py > backend_debug.log 2>&1"
timeout /t 10
echo [3/3] Frontend...
cd frontend-v2
start "Frontend" /B cmd /c "npm run dev -- --port 5173 --host 127.0.0.1 > frontend_debug.log 2>&1"
timeout /t 10
echo Done.
